name: Pull Request

on: pull_request

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color -q
        annotate: warning
